---
apiVersion: v1
kind: Namespace
metadata:
  name: webhook-demo
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: disable-privilege-escalation-mutator-issuer
  namespace: webhook-demo
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: disable-privilege-escalation-mutator-tls
  namespace: webhook-demo
spec:
  secretName: disable-privilege-escalation-mutator-tls
  commonName: disable-privilege-escalation-mutator.webhook-demo.svc
  dnsNames:
    - disable-privilege-escalation-mutator.webhook-demo.svc
  issuerRef:
    name: disable-privilege-escalation-mutator-issuer
    kind: Issuer
  usages:
    - digital signature
    - key encipherment
---
apiVersion: v1
kind: Service
metadata:
  name: disable-privilege-escalation-mutator
  namespace: webhook-demo
spec:
  selector:
    app: disable-privilege-escalation-mutator
  ports:
    - port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disable-privilege-escalation-mutator
  namespace: webhook-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disable-privilege-escalation-mutator
  template:
    metadata:
      labels:
        app: disable-privilege-escalation-mutator
    spec:
      containers:
        - name: mutator
          image: creativsrwr/disable-privilege-escalation-mutator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: disable-privilege-escalation-mutator-tls
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: disable-privilege-escalation-mutator
  annotations:
    cert-manager.io/inject-ca-from: webhook-demo/disable-privilege-escalation-mutator-tls
webhooks:
  - name: disable-privilege-escalation-mutator.webhook-demo.svc
    clientConfig:
      service:
        name: disable-privilege-escalation-mutator
        namespace: webhook-demo
        path: "/mutate"
      caBundle: ""  # injected by cert-manager
    rules:
      - apiGroups: ["apps",""]
        apiVersions: ["v1"]
        resources: ["deployments","pods"]
        operations: ["CREATE","UPDATE"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - webhook-demo
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5

