apiVersion: v1
kind: Pod
metadata:
  name: test-no-escalation
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
        # no securityContext defined here
    

