# docker-security-webhook.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: webhook-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-security-webhook
  namespace: webhook-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-security-webhook
  template:
    metadata:
      labels:
        app: docker-security-webhook
    spec:
      containers:
        - name: webhook
          image: creativsrwr/docker-security-webhook:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          projected:
            sources:
              - secret:
                  name: docker-security-webhook-tls

---
apiVersion: v1
kind: Service
metadata:
  name: docker-security-webhook
  namespace: webhook-demo
spec:
  selector:
    app: docker-security-webhook
  ports:
    - port: 443
      targetPort: 8443

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: docker-security-webhook-issuer
  namespace: webhook-demo
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-security-webhook-tls
  namespace: webhook-demo
spec:
  secretName: docker-security-webhook-tls
  commonName: docker-security-webhook.webhook-demo.svc
  dnsNames:
    - docker-security-webhook.webhook-demo.svc
  issuerRef:
    name: docker-security-webhook-issuer
    kind: Issuer
  usages:
    - digital signature
    - key encipherment

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: docker-security-webhook
  annotations:
    cert-manager.io/inject-ca-from: webhook-demo/docker-security-webhook-tls
webhooks:
  - name: docker-security-webhook.webhook-demo.svc
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - webhook-demo
    clientConfig:
      service:
        name: docker-security-webhook
        namespace: webhook-demo
        path: "/validate"
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
        operations: ["CREATE", "UPDATE"]
        scope: Namespaced
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
