apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-socket-mount
  namespace: default  # Not webhook-demo (enforcement applies)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-socket-mount
  template:
    metadata:
      labels:
        app: docker-socket-mount
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock  # Violation
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
