---
# 1) Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: webhook-demo

---
# 2) Issuer: self-signed
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: env-blocker-webhook-issuer
  namespace: webhook-demo
spec:
  selfSigned: {}

---
# 3) Certificate for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: env-blocker-webhook-tls
  namespace: webhook-demo
spec:
  secretName: env-blocker-webhook-tls
  commonName: env-blocker-webhook.webhook-demo.svc
  dnsNames:
    - env-blocker-webhook.webhook-demo.svc
  issuerRef:
    name: env-blocker-webhook-issuer
    kind: Issuer
  usages:
    - digital signature
    - key encipherment

---
# 4) Service & Deployment for the webhook
apiVersion: v1
kind: Service
metadata:
  name: env-blocker-webhook
  namespace: webhook-demo
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: env-blocker-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-blocker-webhook
  namespace: webhook-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-blocker-webhook
  template:
    metadata:
      labels:
        app: env-blocker-webhook
    spec:
      containers:
        - name: webhook
          image: creativsrwr/env-blocker-webhook:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          projected:
            sources:
              - secret:
                  name: env-blocker-webhook-tls

---
# 5) ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: env-blocker-webhook
  annotations:
  
    cert-manager.io/inject-ca-from: webhook-demo/env-blocker-webhook-tls
webhooks:
  - name: env-blocker-webhook.webhook-demo.svc
    clientConfig:
      service:
        name: env-blocker-webhook
        namespace: webhook-demo
        path: "/validate"
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5

