apiVersion: v1
kind: Pod
metadata:
  name: valid-readonly-rootfs
  namespace: webhook-demo
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      securityContext:
        readOnlyRootFilesystem: true
